title: Does a 30 Hit
email: leinb1dr@gmail.com
description: >- 
  Notes for my D&D campaigns
baseurl: "/D-D-Notes"
domain: "leinb1dr.github.io"
url: "https://leinb1dr.github.io"
github_username:  leinb1dr
theme: minima
plugins:
  - jekyll-feed
  - jemoji
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  parse_block_html: true
collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events
  archivedStories:
    output: true
    permalink: /archived-stories/:path/
    title: Archived Stories